name: meta_weather_api
description: A package manages MetaWeather API.
version: 2.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  freezed_annotation: ^2.0.3
  http: ^1.0.0
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.10
  coverage: ^1.3.1
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mocktail: ^1.0.0
  test: ^1.21.1
